- { name: "Sysctl config", path: "/etc/sysctl.conf", backuponly: true }  # In case of distro change, reinstalling sysctl.conf may not be a good idea
- { name: "Pacman Mirrors", path: "/etc/pacman.d/mirrorlist", onlyon: "arch" }
- { name: "Portages repos", path: "/etc/portage/repos.conf", onlyon: "gentoo" }
- { name: "Package USES", path: "/etc/portage/package.use", onlyon: "gentoo" }
- { name: "Packages Accept Keywords", path: "/etc/portage/package.accept_keywords", onlyon: "gentoo" }
- { name: "Make.conf file", path: "/etc/portage/make.conf", onlyon: "gentoo", backuponly: true }
