name: Build and deploy Documentation
on:
  push:
    branches: [ main ] 
env:
  CARGO_TERM_COLOR: always # Because colors are cool

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Install mdbook to build the book
      - name: Install MDBook
        run: "bash scripts/install-mdbook.sh"
      # Builds the Book to /book
      - name: Build book
        run: mdbook build
      - name: Setup CNAME
        run: "echo kelp.woomy.be >> book/CNAME"
      # Publish to GH pages
      - name: Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
