
name: Build and Deploy
on:
  push:
    branches: [ main ] 
env:
  CARGO_TERM_COLOR: always # Because colors are cool

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install the rust toolchain
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      # Install mdbook to build the book
      - name: Install MDBook
        run: cargo install mdbook
      # Builds the Book to /book
      - name: Build book
        run: mdbook build
      # Publish to GH pages
      - name: Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCES_TOKEN }}
          publish_dir: ./book
