name: AUR package
on:
  push:
          #    tags:
          #- '*'

jobs:
    AUR:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install rust toolchain
          uses: actions-rs/toochain@v1.0.6
          with:
            toolchain:
              stable
        - name: Test repo
          run: cargo test
        - name: Install cargo-aur
          run: cargo install cargo-aur
        - name: Run custom packaging script
          run: bash scripts/aur.sh
