---
name: Build, test and deploy new versions
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - '*'

jobs:
  getversion:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.packagever.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Update repositories
        run: sudo apt update
      - name: Install rust
        run: echo '8\n9' | sudo apt install cargo -y
      - name: Get package version
        id: packagever
        run: echo "::set-output name=version::$(cargo pkgid | awk -F ":" '{print $3}')"
        shell: bash
      